apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: maintnet-text-etl-aviation
  namespace: pdm-demo
spec:
  type: Python
  mode: cluster
  image: caovd/pdm-spark-etl:latest
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/pdm/scripts/etl/text_etl_spark.py
  arguments:
    - "--domain"
    - "aviation"
  sparkVersion: "3.5.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 2
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: pv-datasets
  driver:
    cores: 1
    memory: "4g"
    serviceAccount: spark
    volumeMounts:
      - name: data-volume
        mountPath: /mnt/data
    env:
      - name: PDM_STORAGE_ROOT
        value: /mnt/data
  executor:
    cores: 2
    instances: 2
    memory: "4g"
    volumeMounts:
      - name: data-volume
        mountPath: /mnt/data
    env:
      - name: PDM_STORAGE_ROOT
        value: /mnt/data
